GET http://localhost:4004/odata/v4/myservice/travelInitiate

###
POST http://localhost:4004/odata/v4/myservice/travelInitiate
Content-Type: application/json

{
     "ID": "1234590",
    "Employee_Department_department":"Delivery Excellence - on premise",
    "Departure_City_city":"Meerut",
    "Expected_date_of_departure":"2023-09-18",
    "Billable": "N",
    "Customer_Name_name":"Shivani",
    "Place_of_Visit_city":"Delhi",
    "Expected_Date_Of_Arrival":"2023-11-12",
    "Expected_Duration_In_Days":"4",
    "Purpose_of_Visit":"Work",
    "Expected_Date_Of_Return":"2022-08-13"
}

###
DELETE http://localhost:4004/odata/v4/myservice/travelInitiate/1234590